name: Security Scan - Grype (SCA)

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  grype_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # Allows checkout to read repository content
      security-events: write # Allows upload-sarif to write results to Code Scanning
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Scan Project for Vulnerabilities (Generate SARIF)
        uses: anchore/scan-action@v3 
        id: scan
        with:
          path: .
          fail-build: true
          # FIXED: Set cutoff to 'high' to catch High and Critical
          severity-cutoff: high 
          # FIXED: Output in SARIF format for the next step
          output-format: sarif
          # NOTE: The old 'upload-sarif: true' is removed entirely
          
      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          # Use the SARIF file generated by the previous step
          sarif_file: ${{ steps.scan.outputs.sarif }}
        
      - name: Generate SBOM (for artifact storage/auditing)
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.json
